[workspace]
members = [
    "algo",
    "node-binding",
    "python-binding",
    "roaring-bitmap-nj-binding",
]
resolver = "2"

[workspace.dependencies]
algo = { path = "algo" }

[profile.release]
lto = true
