/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type NjRoaringBitmap = RoaringBitmap
export declare class RoaringBitmap {
  constructor()
  insert(value: number): boolean
  append(values: Array<number>): number
  clear(): void
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  min(): number | null
  isDisjoint(other: RoaringBitmap): boolean
  isSubset(other: RoaringBitmap): boolean
  isSuperset(other: RoaringBitmap): boolean
  static full(): RoaringBitmap
  push(value: number): boolean
  remove(value: number): boolean
  contains(value: number): boolean
  max(): number | null
  rank(value: number): number
  select(n: number): number | null
  removeSmallest(n: number): void
  removeBiggest(n: number): void
}
